FROM gradle:5.4.1-jdk8 AS builder
WORKDIR /app

COPY ./events/src /app/events/src
COPY ./events/build.gradle.kts /app/events
COPY ./bot/src /app/bot/src
COPY ./bot/build.gradle.kts /app/bot
COPY ./db-import/src /app/db-import/src
COPY ./db-import/build.gradle.kts /app/db-import
COPY ./build.gradle.kts /app
COPY ./settings.gradle.kts /app

RUN gradle :bot:build :bot:shadowJar :db-import:build :db-import:shadowJar

FROM openjdk:8-jre-alpine AS bot

ENV APPLICATION_USER bot
RUN adduser -D -g '' $APPLICATION_USER

RUN mkdir /app
RUN chown -R $APPLICATION_USER /app

USER $APPLICATION_USER

COPY --from=builder /app/bot/build/libs/harmony-bot.jar /app/harmony-bot.jar
WORKDIR /app

ENTRYPOINT ["java", "-server", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-XX:InitialRAMFraction=2", "-XX:MinRAMFraction=2", "-XX:MaxRAMFraction=2", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=100", "-XX:+UseStringDeduplication", "-jar", "harmony-bot.jar"]

FROM openjdk:8-jre-alpine AS db-import

ENV APPLICATION_USER dbimport
RUN adduser -D -g '' $APPLICATION_USER

RUN mkdir /app
RUN chown -R $APPLICATION_USER /app

USER $APPLICATION_USER

COPY --from=builder /app/db-import/build/libs/harmony-db-import.jar /app/harmony-db-import.jar
WORKDIR /app

ENTRYPOINT ["java", "-server", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-XX:InitialRAMFraction=2", "-XX:MinRAMFraction=2", "-XX:MaxRAMFraction=2", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=100", "-XX:+UseStringDeduplication", "-jar", "harmony-db-import.jar"]
