query ChannelMessages($channel: ID!, $paginationMode: PaginationMode!,  $paginationReference: PaginationReference!) {
  messages(channel: $channel, paginationMode: $paginationMode, paginationReference: $paginationReference, limit: 100) {
    id

    author {
      id
      name
      discriminator
      nickname
      bot
      color {
        r
        g
        b
      }
    }

    server

    versions {
      content
      timestamp
    }

    createdAt
    editedAt
    deletedAt

    hasReactions
    hasEmbeds
    hasAttachments
  }
}
