query ChannelMessages($channel: ID!, $after: Timestamp!, $before: Timestamp!) {
  messages(channel: $channel, after: $after, before: $before, limit: 100) {
    author {
      name
      discriminator
      nickname
      color {
        r
        g
        b
      }
    }

    server

    versions {
      content
      timestamp
    }

    createdAt
    editedAt
    deletedAt
  }
}
