query Embeds($message: ID!) {
  embeds(message: $message) {
    id
    type
    title
    description
    url
    color {
      r
      g
      b
    }
    timestamp

    footer {
      text
      iconUrl
      proxyIconUrl
    }
    image {
      width
      height
      proxyUrl
    }
    thumbnail {
      width
      height
      proxyUrl
    }
    video {
      width
      height
      proxyUrl
    }
    provider {
      name
      url
    }
    author {
      name
      url
      iconUrl
      proxyIconUrl
    }

    fields {
      name
      value
      inline
    }
  }
}
