query MessageDetails($message: ID!) {
  messageDetails(message: $message) {
    reactions {
      type
      emoji
      emojiId
      emojiAnimated
      count
    }

    embeds {
      id
      type
      title
      description
      url
      color {
        r
        g
        b
      }
      timestamp

      footer {
        text
        iconUrl
        proxyIconUrl
      }
      images {
        width
        height
        url
        proxyUrl
      }
      thumbnail {
        width
        height
        url
        proxyUrl
      }
      video {
        width
        height
        url
        proxyUrl
      }
      provider {
        name
        url
      }
      author {
        name
        url
        iconUrl
        proxyIconUrl
      }

      fields {
        name
        value
        inline
      }
    }

    attachments {
      type
      name
      url
      proxyUrl
      width
      height
      spoiler
    }
  }
}
