query Reactors($message: ID!, $type: String!, $emoji: String!, $emojiId: ID) {
  reactors(message: $message, type: $type, emoji: $emoji, emojiId: $emojiId) {
    user {
      id
      name
      discriminator
      nickname
    }
    createdAt
    deletedAt
  }
}
