query Search($server: ID!, $parameters: SearchParameters!) {
  search(server: $server, parameters: $parameters) {
    total
    totalPages
    error

    entries {
      channel {
        id
        name
      }

      previous {
        id
        ref

        author {
          id
          name
          discriminator
          nickname
          bot
          color {
            r
            g
            b
          }
          webhookName
        }

        server

        versions {
          content
          timestamp
        }

        createdAt
        editedAt
        deletedAt

        hasEmbeds
        hasAttachments
      }

      message {
        id
        ref

        author {
          id
          name
          discriminator
          nickname
          bot
          color {
            r
            g
            b
          }
          webhookName
        }

        server

        versions {
          content
          timestamp
        }

        createdAt
        editedAt
        deletedAt

        hasEmbeds
        hasAttachments
      }

      next {
        id
        ref

        author {
          id
          name
          discriminator
          nickname
          bot
          color {
            r
            g
            b
          }
          webhookName
        }

        server

        versions {
          content
          timestamp
        }

        createdAt
        editedAt
        deletedAt

        hasEmbeds
        hasAttachments
      }
    }
  }
}
